  language: node_js
  node_js:
    - "lts/*"
  before_script:
    - npm install -g gulp
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
  after_script:
      - npm run test-coverall
  addons:
    firefox:
      "latest"
